### ISSUE TITLE
Add `plugin` command for managing plugins and their configs

### ISSUE THREAD

**Issue by mostafa** [gatewayd-io/gatewayd#122]
The idea is to have a `plugin` subcommand that can do a few things:
- [x] #265
- [x] #266
- [x] #264
- [x] #307
- [x] #309
- [ ] #350
- [x] #475
    - This can be part of https://github.com/gatewayd-io/gatewayd-plugin-sdk/issues/1
    - [ ] `plugin build`: Build plugins
    - [ ] #183 
    - [ ] Check plugin compatibility?
    - [ ] Generate the latest protobuf stubs for the given language
- [ ] #424 

**Requirements**
- The plugins are supposed to be on GitHub for now, which means GitHub is the plugin registry for now, until the following feature is added:
    - https://github.com/gatewayd-io/internal-proposals/issues/8

**Resources**
- https://github.com/schollz/progressbar

**Comment by mostafa** [comment]
The `plugin list` and `plugin install` from local archive are developed and released in the [v0.7.x](https://github.com/gatewayd-io/gatewayd/milestone/8) milestone. The rest will be implemented at later stages.

**Comment by mostafa** [comment]
Some features like `plugin install` flags for updating plugin, backing up plugins config file, and cleaning up after install are developed and released in the [v0.8.x](https://github.com/gatewayd-io/gatewayd/milestone/9) milestone. The rest will be implemented at later stages.

**Comment by mostafa** [comment]
Some features were developed in v0.9.x and the rest will be picked up in other milestones.
