### ISSUE TITLE
`plugin install`: Install a plugin from a remote repository and add its default configuration to `gatewayd_plugins.yaml`

### ISSUE THREAD

**Issue by mostafa** [gatewayd-io/gatewayd#264]
## Tasks
- [x] Add `plugin install` command
- [x] Check if the URL/repository exists
- [x] Check if the chosen architecture exists
- [x] Check if the chosen version exists
- [x] Download latest version of the plugin from the release assets
- [x] Download an specific version of the plugin from the release assets
- [x] Download the `checksums.txt` from the release assets
- [x] Extract the file into the current directory
- [x] Add plugin config to the `plugins` in `gatewayd_plugins.yaml`
- [x] Update plugin path and checksum
- [x] Add pull-only flag without installation
