### ISSUE TITLE
Cross-compile for Windows machines

### ISSUE THREAD

**Issue by mostafa** [gatewayd-io/gatewayd#283]
**Tasks:**
- [x] The `gnet/v2` v0.2.3 is released with experimental Windows support. Currently the [v0.2.3-rc1](https://github.com/panjf2000/gnet/releases/tag/v2.3.0-rc.1) is pre-released for testing.
- [x] Disable (r)syslog support for Windows machine by using [`hashicorp/go-syslog`](https://github.com/hashicorp/go-syslog)
- [ ] Figure out how to translate syscalls to Windows
