### ISSUE TITLE
Revamp `docker-compose.yaml`

### ISSUE THREAD

**Issue by mostafa** [gatewayd-io/gatewayd#376]
Revamp `docker-compose.yaml` and include these:

- [x] Use Docker Hub image with GHCR as alternative: https://github.com/gatewayd-io/gatewayd/commit/ae6e06725d261f40743505d0f05479cdf4a68c8c
- [x] Add [health check](https://docs.gatewayd.io/using-gatewayd/API/#liveness-and-readiness): https://github.com/gatewayd-io/gatewayd/commit/f420709839fcbbaef90d7e7cfbee9b313be5cdef
- [x] Add support for installing plugins (currently only installs the cache plugins):
  - [ ] #486 
- [x] Install cache plugin
- [x] Add `redis` image for cache plugin
- [ ] #487
