### ISSUE TITLE
Implement signal, action and policy system

### ISSUE THREAD

**Issue by mostafa** [gatewayd-io/gatewayd#422]
## Tasks

- [x] https://github.com/gatewayd-io/gatewayd-plugin-sdk/pull/22
- [x] https://github.com/gatewayd-io/gatewayd/pull/451
- [x] #442 
- [x] Fix TODOs or create tickets
  - [x] Add support for running default policy if no policy is matched
  - [x] Check for non-contradictory actions (terminal vs. non-terminal)
  - [x] Update API messages
- [x] Add tests
- [x] https://github.com/gatewayd-io/docs/pull/46

## Related

- #337 
- #399 
- https://github.com/gatewayd-io/proposals/issues/5
- https://github.com/gatewayd-io/act-poc

**Comment by mostafa** [comment]
Further development is tracked in #473.
