### ISSUE TITLE
Ideas for improvement

### ISSUE THREAD

**Issue by mostafa** [gatewayd-io/gatewayd#46]
- [x] #50
- [x] #62
- [x] #60
- [x] #85
- [x] #72
- [x] #76 
- [x] #89
- [x] Investigate [gob](https://pkg.go.dev/encoding/gob) for passing objects to/from plugins (protobuf is more than enough)
- [x] Write tests for `logging/hclog_adapter.go` (#111)
- [x] https://github.com/gatewayd-io/gatewayd-plugin-sdk/issues/1
- [x] #88
- [x] #57 
- [x] Hook types should be introduced. Currently there are two types: notification and normal hooks. Notification hooks are just to notify the plugin that an event happened, while the normal hooks have different purposes. This should be improved.
- [x] The plugin config object should be read and somehow used. Currently it is just loaded into the `PluginImpl.Config` and not used. Other config parameters should be investigated as well.
- [x] Write a proposal for the built-in plugins: https://github.com/gatewayd-io/gatewayd-plugin-proposals
- [x] #147
- [x] #190
- [x] #218
- [ ] #122 
- [ ] https://github.com/gatewayd-io/internal-proposals/issues/8
- [x] #276
- [ ] Review TODOs in code
- [ ] #278
- [x] #279
- [ ] #277
- [ ] #280
