### ISSUE TITLE
`plugin scaffold`: Create a plugin skeleton/scaffold (`init`)

### ISSUE THREAD

**Issue by mostafa** [gatewayd-io/gatewayd#475]
The idea is to quickly create a project based on the plugin template for Go (and another languages), and prepare the env for developers to create plugins.

- [x] Implement plugin scaffolding (#518)
- [x] Add tests (#613)
- [x] Update docs in repo (#528)
- [x] Update docs.gatewayd.io (gatewayd-io/docs#51)

**Comment by zeina1i** [comment]
Hey @mostafa 

Can I take this task?
If so, I need to take a look on plugins structure, and get back to you by proposal/questions.

**Comment by mostafa** [comment]
Hey @zeina1i,

Sure! This might need some more work on other projects as well, like [plugin-template-go](https://github.com/gatewayd-io/plugin-template-go), specifically [this issue](https://github.com/gatewayd-io/plugin-template-go/issues/6).

**Comment by zeina1i** [comment]
@mostafa cool. Thanks for the hint

**Comment by mostafa** [comment]
Hey @zeina1i,

Are there any updates?

**Comment by zeina1i** [comment]
Hey @mostafa 

It's still in progress. But should be delivered in the weekend. I will keep you updated you anyways🙏

**Comment by mostafa** [comment]
Hey @zeina1i,

I saw that you made some progress on [this repo](https://github.com/gatewayd-io/plugin-template-go-cookiecutter/tree/test). Is this still in progress or do you consider it done?

**Comment by zeina1i** [comment]
Hey @mostafa 

This repo can be removed. As I transferred its code to the core repo.
I am almost there.and make the pr in the weekend.🙏

**Comment by mostafa** [comment]
I'll archive it until you make the new PR, then I'll remove it. Is that okay?

**Comment by zeina1i** [comment]
@mostafa 
Yes, thank you🙏

**Comment by mostafa** [comment]
Hey @zeina1i,

Will you have time to work on the tests?
