### ISSUE TITLE
Add circuit-breakers, retries and related patterns to deal with timeouts and other mishaps

### ISSUE THREAD

**Issue by mostafa** [gatewayd-io/gatewayd#90]
## Tasks
- [x] Identify all (or most of) the areas in code that might need circuit-breaking and add circuit-breakers  (retry, timeout, etc.) to those areas:
  - [x] `cmd/run.go`:
    - [x] Plugin start timeout
    - [ ] ~rsyslog dial timeout~ ([Go doesn't support it](https://github.com/golang/go/issues/62285))
    - [x] Metrics server and handler timeouts
  - [x] `network/client.go`:
    - [x] Dial timeout
    - [x] Fix other timeouts
  - [x] Add retry logic
    - [x] `network/client`
    - [ ] ~`network/server`~
    - [ ] ~`network/proxy`?~
    - [ ] ~`network/conn_wrapper`~
- [x] Write tests

## Resources
- https://github.com/Netflix/Hystrix
- https://github.com/afex/hystrix-go
- https://github.com/sony/gobreaker
- https://github.com/rubyist/circuitbreaker
- https://github.com/cep21/circuit
- https://en.wikipedia.org/wiki/Circuit_breaker_design_pattern
- https://medium.com/@homayoonalimohammadi/circuitbreakers-in-go-d85f5297cb50
